config/routes.rb
AlchemyCrm::Engine.routes.draw do

  match '/recipients/:h/reads' => 'recipients#reads',
    :as => 'recipient_reads'

  match '/recipients/:h/reacts' => 'recipients#reacts',
    :as => 'recipient_reacts'

  match '/subscriptions/:token/destroy/:newsletter_id' => 'subscriptions#destroy',
    :as => 'destroy_subscription'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/contacts/:token/verify' => 'contacts#verify',
    :as => 'verify_contact'

  match '/contacts/:token/disable' => 'contacts#disable',
    :as => 'disable_contact'

  match '/mailings/:m/show/:r' => 'mailings#show',
    :as => 'show_mailing'

  resources :mailings, :only => [:show]

  resources :contacts do
    collection do
      post :signup, :signout
    end
  end

  resources :subscriptions do
    collection do
      post :overview
    end
  end

  namespace :admin do

    resources :contacts do
      collection do
        get :import
        get :autocomplete_tag_list
        post :import
      end
      member { get :export }
    end

    resources :contact_groups do
      collection { get :add_filter }
    end

    resources :newsletters

    resources :deliveries

    resources :mailings do
      resources :deliveries
      collection { get :signout }
      member do
        get :copy
        get :edit_content
      end
    end

  end

end

app/controllers/alchemy_crm/admin/contacts_controller.rb
# encoding: UTF-8

module AlchemyCrm
  module Admin
    class ContactsController < AlchemyCrm::Admin::BaseController

      include CSVMagic::ControllerActions

      csv_magic_config(
        :mapping => {
          Contact.clean_human_attribute_name(:salutation)  => :salutation,
          Contact.clean_human_attribute_name(:title)       => :title,
          Contact.clean_human_attribute_name(:firstname)   => :firstname,
          Contact.clean_human_attribute_name(:lastname)    => :lastname,
          Contact.clean_human_attribute_name(:email)       => :email,
          Contact.clean_human_attribute_name(:company)     => :company,
          Contact.clean_human_attribute_name(:address)     => :address,
          Contact.clean_human_attribute_name(:zip)         => :zip,
          Contact.clean_human_attribute_name(:city)        => :city,
          Contact.clean_human_attribute_name(:country)     => :country,
          Contact.clean_human_attribute_name(:phone)       => :phone,
          Contact.clean_human_attribute_name(:mobile)      => :mobile,
          Contact.human_attribute_name(:tag_list)          => :tag_list,
          Contact.human_attribute_name(:verified)          => :verified,
          Contact.human_attribute_name(:disabled)          => :disabled
        }
      )

      before_filter :load_tags, :only => [:new, :edit]

      def index
        if params[:query].blank?
          @contacts = Contact.scoped
        else
          search_terms = ActiveRecord::Base.sanitize("%#{params[:query]}%")
          @contacts = Contact.where(Contact::SEARCHABLE_ATTRIBUTES.map { |attribute|
            "#{Contact.table_name}.#{attribute} LIKE #{search_terms}"
          }.join(" OR "))
        end
        respond_to do |format|
          format.html {
            @contacts = @contacts.page(params[:page] || 1).per(per_page_value_for_screen_size)
          }
          format.csv {
            export_file_as(:csv)
          }
          format.xls {
            export_file_as(:xls)
          }
        end
      end

      def new
        @contact = Contact.new(:country => ::I18n.locale.to_s.upcase)
        render :layout => false
      end

      def import
        render :layout => !request.xhr?
      end

      def mass_create
        if params[:verified] == "1"
          if params[:filename] || params[:file]
            handle_file_request
          else
            @error = build_error_message(alchemy_crm_t(:missing_file))
          end
        else
          @error = build_error_message(alchemy_crm_t(:imported_contacts_not_verified))
        end
      end

      def export
        if params[:id].present?
          @contact = Contact.find(params[:id])
          @contact.to_vcard
          send_file("#{Rails.root.to_s}/tmp/#{@contact.fullname}.vcf")
        else
          render :layout => false
        end
      end

      def autocomplete_tag_list
        items = ActsAsTaggableOn::Tag.where(['LOWER(name) LIKE ?', "#{params[:term].downcase}%"])
        render :json => json_for_autocomplete(items, :name)
      end

    private

      def load_tags
        @tags = ActsAsTaggableOn::Tag.order("name ASC").all
        @tags = @tags - @contact.tags.to_a unless @contact.nil?
      end

      def build_error_message(message)
        heading = "<h1>#{alchemy_crm_t(:errors_while_importing)}</h1>".html_safe
        message = "<p>#{message}</p>".html_safe
        heading + message
      end

      # TODO: Make this with mass_create
      def create_resource_items_from_csv(*args)
        @csv_import_errors = []
        @contacts = []
        reader = CSVMagic::Reader.new(params)
        reader.each do |row|
          @contacts << contact = Contact.new(row)
          contact.verified = true
          unless contact.save
            @csv_import_errors.push [contact, contact.errors]
          end
        end
        @valid_contacts = @contacts.select(&:valid?)
        reader.remove_file if @csv_import_errors.empty?
      end

      def render_csv_import_form
        render 'import'
      end

      def handle_file_request
        if params[:fields] || !is_vcard_file?(params[:file])
          handle_csv_post_request
        else
          handle_vcf_post_request
        end
      end

      def handle_vcf_post_request
        @contacts = Contact.new_from_vcard(params[:file], true)
        if @contacts.empty?
          flash[:error] = alchemy_crm_t(:no_contacts_imported)
        elsif @contacts.detect(&:invalid?).nil?
          flash[:notice] = alchemy_crm_t(:successfully_imported_contacts)
        else
          @errors = build_error_message(alchemy_crm_t(:please_check_highlighted_vcards_on_errors))
        end
        @valid_contacts = @contacts.select(&:valid?) || []
        render :vcf_import_result
      end

      def is_vcard_file?(file)
        content = file.read
        file.rewind
        content.starts_with?("BEGIN:VCARD")
      end

      def export_file_as(format)
        @columns = AlchemyCrm::Contact::EXPORTABLE_COLUMNS
        filename = "#{AlchemyCrm::Contact.model_name.human(:count => @contacts.count)}-#{Time.now.strftime('%Y-%m-%d_%H-%M')}"
        send_data render_to_string, :type => format.to_sym, :filename => "#{filename}.#{format}"
      end

    end
  end
end

app/controllers/alchemy_crm/contacts_controller.rb
# encoding: UTF-8
module AlchemyCrm
  class ContactsController < AlchemyCrm::BaseController

    helper 'Alchemy::Pages'
    layout :layout_for_page

    before_filter :load_signup_form, :only => [:show, :signup, :verify]
    before_filter :load_signout_form, :only => [:signout, :disable]

    def show
      @page = @element.page
      @root_page = @page.get_language_root
      render :template => 'alchemy/pages/show'
    end

    def signup
      @contact = Contact.find_or_initialize_by_email(params[:contact])
      enable_contact if @contact.disabled?
      if @contact.save
        ContactsMailer.signup_mail(
          @contact,
          Alchemy::Page.find_by_page_layout_and_language_id('newsletter_mails', session[:language_id])
        ).deliver
        @contact_signed_up = true
      else
        @contact_signed_up = false
      end
      @page = @element.page
      @root_page = @page.get_language_root
      render :template => 'alchemy/pages/show'
    end

    def verify
      @contact = Contact.find_by_email_sha1(params[:token])
      if @contact
        @contact_verified = @contact.update_attribute(:verified, true)
        @page = @element.page
        @root_page = @page.get_language_root
        render :template => 'alchemy/pages/show'
      else
        contact_not_found
      end
    end

    def signout
      @contact = Contact.find_by_email_and_verified(params[:email], true)
      if @contact.blank?
        flash[:notice] = ::I18n.t(:contact_unknown, :scope => :alchemy_crm)
        @contact_signed_out = false
      else
        ContactsMailer.signout_mail(
          @contact,
          Alchemy::Page.find_by_page_layout_and_language_id('newsletter_mails', session[:language_id])
        ).deliver
        @contact_signed_out = true
      end
      @page = @element.page
      @root_page = @page.get_language_root
      render :template => 'alchemy/pages/show'
    end

    def disable
      @contact = Contact.find_by_email_sha1(params[:token])
      if @contact
        @contact_disabled = @contact.disable!
        @page = @element.page
        @root_page = @page.get_language_root
        render :template => 'alchemy/pages/show'
      else
        contact_not_found
      end
    end

  private

    def load_signup_form
      @element = Alchemy::Element.find_by_name('newsletter_signup_form')
      if @element.blank?
        raise ActiveRecord::RecordNotFound, "Alchemy::Element with name 'newsletter_signup_form' not found!"
      end
    end

    def load_signout_form
      @element = Alchemy::Element.find_by_name('newsletter_signout_form')
      if @element.blank?
        raise ActiveRecord::RecordNotFound, "Alchemy::Element with name 'newsletter_signout_form' not found!"
      end
    end

    def contact_not_found
      raise ActionController::RoutingError.new('Contact Not Found')
    end

    def enable_contact
      @contact.disabled = false
      if params[:contact][:subscriptions_attributes].present?
        params[:contact][:subscriptions_attributes].each do |i, subscription_attributes|
          @contact.subscriptions.new(subscription_attributes)
        end
      end
    end

  end
end

app/views/alchemy_crm/admin/contacts/_contact.html.erb
<tr class="<%= cycle('even', 'odd') %><%= contact.disabled? ? ' disabled' : nil %>">
  <td class="icon">
    <%= content_tag('span', '', :class => 'icon contact') %>
  </td>
  <td class="name" style="width: 180px">
    <%= contact.lastname %>
  </td>
  <td class="name" style="width: 180px">
    <%= contact.firstname %>
  </td>
  <td class="name"><%= contact.company %></td>
  <td class="email"><%= contact.email %></td>
  <td class="tags">
    <%- contact.tags.each do |tag| -%>
      <%= content_tag(:span, tag.name, :class => 'tag') %>
    <%- end -%>
  </td>
  <td><%= contact.newsletters.collect(&:name).join(', ') %></td>
  <td class="center"><%= render_icon contact.verified? && !contact.disabled %></td>
  <td class="tools">
    <%= link_to_overlay_window(
      '',
      edit_admin_contact_path(contact),
      {
        :title => alchemy_crm_t(:edit_contact),
        :size => '415x560'
      },
      {
        :title => alchemy_crm_t(:edit_contact),
        :class => 'icon contact_edit'
      }
    ) -%>
    <%= link_to(
      '',
      export_admin_contact_path(contact),
      {
        :title => alchemy_crm_t(:export_contact),
        :class => 'icon contact_export'
      }
    ) -%>
    <%= link_to_confirmation_window(
      "",
      alchemy_crm_t(:do_you_really_want_to_delete_this_contact?),
      admin_contact_path(contact),
      :title => alchemy_crm_t(:delete_contact),
      :class => 'icon contact_delete'
    ) %>
  </td>
</tr>

app/views/alchemy_crm/admin/contacts/_form.html.erb
<%= form_for [:admin, @contact], :remote => true do |f| %>
<div id="errors" style="display:none"></div>
<% if @contact.disabled? -%>
<div class="info">
  <%= render_icon(:info) %>
  <p>
    <strong><%= alchemy_crm_t(:contact_is_disabled_notice) %></strong>
  </p>
</div>
<% end -%>
<table id="contact">
  <tr>
    <td class="label"><%= f.label :salutation %></td>
    <td class="select">
      <%= f.select(:salutation,
        options_for_select([
          [t('Please choose'), ''],
          [alchemy_crm_t(:mr, :scope => 'salutations'), :mr],
          [alchemy_crm_t(:ms, :scope => 'salutations'), :ms]
        ], @contact.salutation), {}, { :class => 'alchemy_selectbox very_short' }) %>
    </td>
    <td class="label right"><%= f.label :title %></td>
    <td class="input"><%= f.text_field :title, :class => "thin_border medium_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :firstname %></td>
    <td colspan="3" class="input"><%= f.text_field :firstname, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :lastname %></td>
    <td colspan="3" class="input"><%= f.text_field :lastname, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :company %></td>
    <td colspan="3" class="input"><%= f.text_field :company, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :email %></td>
    <td colspan="3" class="input"><%= f.text_field :email, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :phone %></td>
    <td colspan="3" class="input"><%= f.text_field :phone, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :mobile %></td>
    <td colspan="3" class="input"><%= f.text_field :mobile, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :address %></td>
    <td colspan="3" class="input"><%= f.text_field :address, :class => "thin_border very_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :zip %></td>
    <td class="input"><%= f.text_field :zip, :class => "thin_border short" %></td>
    <td class="label right"><%= f.label :city %></td>
    <td class="input"><%= f.text_field :city, :class => "thin_border medium_long" %></td>
  </tr>
  <tr>
    <td class="label"><%= f.label :country %></td>
    <td colspan="3" class="input">
      <%= f.country_select :country, {}, {:include_blank => t('Please choose')}, {:class => "alchemy_selectbox very_long"} %>
    </td>
  </tr>
  <tr>
    <td class="label"><%= f.label :tag_list %></td>
    <td colspan="3" class="input">
      <%= f.autocomplete_field :tag_list, autocomplete_tag_list_admin_contacts_path, :class => "thin_border very_long", 'data-delimiter' => ',' %>
      <p><small>*<%= alchemy_crm_t(:seperate_tags_with_comma) %></small></p>
    </td>
  </tr>
  <tr>
    <td class="label">Status</td>
    <td class="checkbox" colspan="3">
      <%= f.check_box :verified %>
      <%= f.label :verified %>
      <%= f.check_box :disabled %>
      <%= f.label :disabled %>
    </td>
  </tr>
  <tr>
    <td class="submit" colspan="4"><%= f.button t(:save), :class => "button" %></td>
  </tr>
</table>

<% end %>

app/views/alchemy_crm/admin/contacts/_import_form.html.erb
<%= form_tag mass_create_admin_contacts_path, :remote => request.xhr?, :multipart => true, :class => 'contact_import' do %>
  <div class="info">
    <%= render_icon('info') %>
    <h1><%= alchemy_crm_t(:headline, :scope => 'import_format_notice') %></h1>
    <ul>
      <li><%= alchemy_crm_t(:vcf_format, :scope => 'import_format_notice') %></li>
      <li><%= alchemy_crm_t(:csv_format, :scope => 'import_format_notice') %></li>
    </ul>
  </div>

  <div id="errors" style="display: none"></div>

  <table>
    <tr>
      <td class="label"><%= label_tag :file, alchemy_crm_t(:file) %></td>
      <td><%= file_field_tag :file %></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= check_box_tag :verified %>
        <%= label_tag :verified, alchemy_crm_t(:import_contacts_verified) %>
      </td>
    </tr>
    <tr>
      <td class="submit" colspan="2">
        <%= button_tag alchemy_crm_t(:import), :name => nil, :class => 'button' %>
      </td>
    </tr>
  </table>

<% end %>

app/views/alchemy_crm/admin/contacts/export.html.erb
<div class="with_padding">
  <p><%= alchemy_crm_t('Please choose format') %></p>
  <table id="export_format">
    <tr>
      <td class="submit">
        <%= link_to(
          'Excel',
          alchemy_crm.admin_contacts_path(
            :format => :xls,
            :query => params[:query]
          ),
          :class => 'button'
        ) %>
      </td>
    </tr>
    <tr>
      <td class="submit">
        <%= link_to(
          'CSV',
          alchemy_crm.admin_contacts_path(
            :format => :csv,
            :query => params[:query]
          ),
          :class => 'button'
        ) %>
      </td>
    </tr>
  </table>
</div>
<script type="text/javascript">
  $('.button', '#export_format').on('click', Alchemy.closeCurrentWindow);
</script>

app/views/alchemy_crm/admin/contacts/import.html.erb
<%= render 'import_form' %>

app/views/alchemy_crm/admin/contacts/import.js.erb
$('div#errors').html('<%= @error -%>').show();
Alchemy.enableButton('button.button');

app/views/alchemy_crm/admin/contacts/import_result.html.erb
<%- content_for(:javascript_includes) do -%>
	<%= javascript_include_tag "alchemy_crm/scripts.js" %>
<%- end -%>

<%- content_for(:stylesheets) do -%>
	<%= stylesheet_link_tag('alchemy_crm/styles') %>
<%- end -%>

<% toolbar(
	:buttons => [
		{
			:icon => :close,
			:label => t(:cancel),
			:url => alchemy_crm.admin_contacts_path,
			:title => t(:cancel),
			:overlay => false,
			:if_permitted_to => [:index, :alchemy_crm_admin_contacts]
		}
	],
	:search => false
) -%>

<h1><%= alchemy_crm_t('Import result') %></h1>

<% if @errors -%>

<div id="errors">
	<%= @errors %>
</div>

<% if @contacts -%>
<div class="info">
	<%= render_icon(:info) %>
	<p><%= alchemy_crm_t(:contacts_imported_with_errors_notice) %></p>
</div>
<% end -%>

<%= render "import_form" %>

<% end -%>

<% if @contacts -%>

<table>
	<tr>
		<th><%= translate_model_attribute(:contact, :name) %></th>
		<th><%= translate_model_attribute(:contact, :email) %></th>
		<th><%= alchemy_crm_t(:import_status) %></th>
	</tr>
<% @contacts.each do |contact| -%>
	<tr class="<%= cycle("even", "odd") %><%= contact.invalid? ? ' disabled' : nil -%>">
		<td><%= contact.fullname %></td>
		<td><%= contact.email %></td>
		<td>
			<% if contact.valid? -%>
			<%= render_icon(:true) %>
			<% else -%>
			<%= contact.errors.full_messages.join('<br>') %>
			<% end -%>
		</td>
	</tr>
<% end -%>
</table>

<% end -%>

app/views/alchemy_crm/admin/contacts/index.csv.erb
<% csv = CSV.generate(:col_sep => ";", :row_sep => "\r\n", :force_quotes => true) do |csv| %>
  <% csv << @columns.map { |h| AlchemyCrm::Contact.human_attribute_name(h) } %>
  <% @contacts.each do |contact| %>
    <%
    csv << @columns.map do |a|
      value = contact.send(a).to_s.strip
      if a == 'salutation' && !value.blank?
        ::I18n.t(value.to_sym, :scope => 'alchemy_crm.salutations', :default => value)
      elsif !value.blank? && a == 'verified' || a == 'disabled'
        alchemy_crm_t(value.to_sym)
      else
        value
      end
    end %>
  <% end %>
<% end %>
<%= raw csv %>

app/views/alchemy_crm/admin/contacts/index.html.erb
<% content_for(:javascript_includes) do -%>
  <%= javascript_include_tag "alchemy_crm/scripts.js" %>
<% end -%>

<% content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag('alchemy_crm/styles') %>
<% end -%>

<% toolbar(
  :buttons => [
    {
      :icon => "contact_add",
      :label => alchemy_crm_t(:add_contact),
      :url => alchemy_crm.new_admin_contact_path,
      :title => alchemy_crm_t(:add_contact),
      :overlay_options => {
        :title => alchemy_crm_t(:add_contact),
        :size => '415x560'
      },
      :if_permitted_to => [:new, :alchemy_crm_admin_contacts]
    },
    {
      :icon => :contact_import,
      :label => alchemy_crm_t(:import_contacts),
      :url => alchemy_crm.import_admin_contacts_path,
      :title => alchemy_crm_t(:import_contacts),
      :overlay_options => {
        :title => alchemy_crm_t(:import_contacts),
        :size => '400x300'
      },
      :if_permitted_to => [:import, :alchemy_crm_admin_contacts]
    },
    {
      :icon => :file_download,
      :label => alchemy_crm_t(:export_contacts),
      :url => alchemy_crm.export_admin_contacts_path(:query => params[:query]),
      :title => alchemy_crm_t(:export_contacts),
      :overlay_options => {
        :title => alchemy_crm_t(:export_contacts),
        :size => '200x150'
      },
      :if_permitted_to => [:index, :alchemy_crm_admin_contacts]
    }
  ]
) %>

<table class="list">
  <%- unless @contacts.blank? -%>
  <tr>
    <th class="icon"></th>
    <th class="name" style="width: 180px"><%= translate_model_attribute(:contact, :lastname).gsub(/\*$/, '') %></th>
    <th class="name" style="width: 180px"><%= translate_model_attribute(:contact, :firstname).gsub(/\*$/, '') %></th>
    <th class="name"><%= translate_model_attribute(:contact, :company) %></th>
    <th class="name"><%= translate_model_attribute(:contact, :email).gsub(/\*$/, '') %></th>
    <th class="name"><%= translate_model_attribute(:contact, :tags) %></th>
    <th><%= translate_model_attribute(:contact, :newsletters) %></th>
    <th class="center"><%= translate_model_attribute(:contact, :verified) %></th>
    <th class="tools" style="width: 60px"></th>
  </tr>
  <%- end -%>
  <%= render @contacts %>
</table>
<%= render 'alchemy/admin/partials/pagination_links', :items => @contacts, :scope => alchemy_crm %>

app/views/alchemy_crm/admin/contacts/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="<%= AlchemyCrm::Contact.model_name.human(:count => @contacts.count) -%>">
    <Table>
      <Row>
      <% @columns.each do |col| %>
        <Cell>
          <Data ss:Type="String"><%= AlchemyCrm::Contact.human_attribute_name(col) %></Data>
        </Cell>
      <% end %>
      </Row>
    <% @contacts.each do |contact| %>
      <Row>
      <% @columns.each do |col| %>
        <% value = contact.send(col).to_s.strip %>
        <Cell>
        <% if col == 'salutation' && !value.blank? %>
          <Data ss:Type="String"><%= ::I18n.t(value.to_sym, :scope => 'alchemy_crm.salutations', :default => value) %></Data>
        <% elsif !value.blank? && (col == 'verified' || col == 'disabled') %>
          <Data ss:Type="String"><%= alchemy_crm_t(value) %></Data>
        <% else %>
          <Data ss:Type="String"><%= value %></Data>
        <% end %>
        </Cell>
      <% end %>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/alchemy_crm/admin/contacts/mass_create.html.erb
<% toolbar(
  :buttons => [
    {
      :icon => :close,
      :label => t(:cancel),
      :url => alchemy_crm.admin_contacts_path,
      :title => t(:cancel),
      :overlay => false,
      :if_permitted_to => [:index, :alchemy_crm_admin_contacts]
    }
  ],
  :search => false
) %>

<% if @error %>
<div id="errors">
  <%= @error %>
</div>
<% end %>
<%= render 'import_form' %>

app/views/alchemy_crm/admin/contacts/mass_create.js.erb
$('div#errors').html('<%= @error -%>').show();
Alchemy.enableButton('button.button');

app/views/alchemy_crm/admin/contacts/new.html.erb
<%= render :partial => "form" %>

app/views/alchemy_crm/admin/contacts/vcf_import_result.html.erb
<%- content_for(:javascript_includes) do -%>
  <%= javascript_include_tag "alchemy_crm/scripts.js" %>
<%- end -%>

<%- content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag('alchemy_crm/styles') %>
<%- end -%>

<h1><%= alchemy_crm_t('Import result') %></h1>

<% if @valid_contacts.any? -%>
<div class="flash notice" style="margin: 8px 0">
  <%= render_icon('true') %>
  <%= alchemy_crm_t('%{count} contacts imported successfully') % {:count => @valid_contacts.length} %>
</div>
<% end -%>

<% if @errors -%>
<div class="flash error" style="margin: 8px 0">
  <%= render_icon('error') %><%= @errors %>
</div>
<% end -%>

<% if @contacts.any? -%>
<table>
  <tr>
    <th><%= translate_model_attribute(:contact, :name) %></th>
    <th><%= translate_model_attribute(:contact, :email).gsub(/\*$/, '') %></th>
    <th><%= alchemy_crm_t(:import_status) %></th>
  </tr>
  <% @contacts.each do |contact| -%>
  <tr class="<%= cycle("even", "odd") %><%= contact.invalid? ? ' disabled' : nil -%>">
    <td><%= contact.fullname %></td>
    <td><%= contact.email %></td>
    <td>
      <% if contact.valid? -%>
      <%= render_icon(:true) %>
      <% else -%>
      <%= contact.errors.full_messages.join('<br>') %>
      <% end -%>
    </td>
  </tr>
  <% end -%>
</table>
<% else -%>
<p><%= alchemy_crm_t(:no_contacts_imported) %></p>
<% end -%>

<p style="margin: 8px 0; height: 25px">
  <%= link_to t(:continue), admin_contacts_path, :class => 'button' %>
</p>