config/routes.rb
AlchemyCrm::Engine.routes.draw do

  match '/recipients/:h/reads' => 'recipients#reads',
    :as => 'recipient_reads'

  match '/recipients/:h/reacts' => 'recipients#reacts',
    :as => 'recipient_reacts'

  match '/subscriptions/:token/destroy/:newsletter_id' => 'subscriptions#destroy',
    :as => 'destroy_subscription'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/admin/elements/teasables' => 'admin/elements#teasables',
    :as => 'teasable_elements'

  match '/contacts/:token/verify' => 'contacts#verify',
    :as => 'verify_contact'

  match '/contacts/:token/disable' => 'contacts#disable',
    :as => 'disable_contact'

  match '/mailings/:m/show/:r' => 'mailings#show',
    :as => 'show_mailing'

  resources :mailings, :only => [:show]

  resources :contacts do
    collection do
      post :signup, :signout
    end
  end

  resources :subscriptions do
    collection do
      post :overview
    end
  end

  namespace :admin do

    resources :contacts do
      collection do
        get :import
        get :autocomplete_tag_list
        post :import
      end
      member { get :export }
    end

    resources :contact_groups do
      collection { get :add_filter }
    end

    resources :newsletters

    resources :deliveries

    resources :mailings do
      resources :deliveries
      collection { get :signout }
      member do
        get :copy
        get :edit_content
      end
    end

  end

end

app/views/csv_magic/import_errors.html.erb
<%- content_for(:javascript_includes) do -%>
  <%= javascript_include_tag "alchemy_crm/scripts.js" %>
<%- end -%>

<%- content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag('alchemy_crm/styles') %>
<%- end -%>

<% if @valid_contacts.present? -%>
<div class="flash notice" style="margin: 8px 0">
  <%= render_icon('true') %>
  <%= alchemy_crm_t('%{count} contacts imported successfully') % {:count => @valid_contacts.length} %>
</div>
<% end -%>

<h1><%= alchemy_crm_t(:errors_while_importing_contacts) %></h1>

<div class="info">
  <%= render_icon('info') %>
  <p><%= alchemy_crm_t(:contacts_imported_with_errors_notice) %></p>
</div>

<table class="list" style="margin-bottom: 1em">
  <tr>
    <th><%= translate_model_attribute(:contact, :name).gsub(/\*$/, '') %></th>
    <th><%= translate_model_attribute(:contact, :email).gsub(/\*$/, '') %></th>
    <th><%= alchemy_crm_t(:errors) %></th>
  </tr>
  <% @csv_import_errors.each do |error| -%>
  <tr class="<%= cycle("even", "odd") -%>">
    <td><%= error.first.fullname -%></td>
    <td><%= error.first.email -%></td>
    <td>
      <% error[1].full_messages.each do |message| -%>
      <p><%= message -%></p>
      <% end -%>
    </td>
  </tr>
  <% end -%>
</table>

<p style="margin: 8px 0; height: 25px">
  <%= link_to t(:continue), admin_contacts_path, :class => 'button' %>
</p>

app/views/csv_magic/mapper.html.erb
<%- content_for(:javascript_includes) do -%>
  <%= javascript_include_tag "alchemy_crm/scripts.js" %>
<%- end -%>

<%- content_for(:stylesheets) do -%>
  <%= stylesheet_link_tag('alchemy_crm/styles') %>
<%- end -%>

<% toolbar(
  :buttons => [
    {
      :icon => :close,
      :label => t(:cancel),
      :url => alchemy_crm.admin_contacts_path,
      :title => t(:cancel),
      :overlay => false,
      :if_permitted_to => [:index, :alchemy_crm_admin_contacts]
    }
  ],
  :search => false
) -%>

<h1><%= alchemy_crm_t(:import_contacts_from_csv_file) %></h1>

<div class="info">
  <%= render_icon('info') %>
  <p><%= alchemy_crm_t(:map_columns) %></p>
</div>

<%= form_tag nil, :id => 'map_fields_form', :method => :post do -%>
  <%= hidden_field_tag :filename, @mapper.filename %>
  <table class="list">
    <tr>
      <%- header = @raw_data.first -%>
      <%- header.size.times do |column_index| -%>
      <th>
        <%= select_tag("fields[#{column_index + 1}]", options_for_select(
          @mapper.map_fields,
          header[column_index].to_s.to_sym
        ), :include_blank => true, :class => 'alchemy_selectbox medium') %>
      </th>
      <%- end -%>
    </tr>
    <%- @raw_data[0..5].each do |row| -%>
    <tr class="<%= cycle('even', 'odd') -%>">
      <%- row.each do |column| -%>
      <td><%= h(column) -%></td>
      <%- end -%>
    </tr>
    <%- end -%>
  </table>
  <div class="with_padding">
    <p>
      <%= check_box_tag 'ignore_first_row', '1', true %>
      <%= label_tag 'ignore_first_row', alchemy_crm_t(:ignore_first_row) %>
    </p>
  </div>
  <div class="action">
    <%= hidden_field_tag :verified, params[:verified] %>
    <%= button_tag alchemy_crm_t(:import), :name => nil, :class => 'button' %>
  </div>
<%- end -%>